[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

#[[main]]
#    identifier = "about"
#    name = "About me"
#    url = "/about"
#    weight = 2

[[main]]
    identifier = "about"
    name = "About me"
    url = "/cv"
    weight = 2

[[main]]
    identifier = "scholar"
    name = "Scholar"
    url = "https://scholar.google.com/citations?user=uohjTAQAAAAJ&hl=en"
    weight = 3

[[main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 4

[[main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 5

# [[main]]
#    identifier = "donate"
#    name = "Donate"
#    url = "https://ko-fi.com/nixentric"
#    weight = 5
    
# Social Media Configuration

[[social]]
    identifier = "twitter"
    name = "Twitter"
    url = "#"
    weight = 1


[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/phamquang-hieu"
    weight = 2